apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trigo-apps-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "app-a.com"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: app-a-app-a-svc
            port:
              number: 80
  - host: "app_b.com"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: app-b-app-b-svc
            port:
              number: 80
